[package]
name = "octatools"
version = "0.1.0"
edition = "2021"
readme = "README.md"
exclude = ["/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"]

[[bin]]
name = "octatools"
path = "src/main.rs"

[lib]
name = "serde_octatrack"
path = "serde_octatrack/src/lib.rs"

[dependencies]
aifc = "0.5.3"
base16ct = "0.2.0"
base64ct = "1.6.0"
bincode = "1.3.3"
clap = { version = "4.5.20", features = ["derive"] }
clap_complete = "4.5.33"
copy_dir = "0.1.3"
csv = "1.3.0"
env_logger = "0.11.5"
hex-literal = "0.4.1"
hound = "3.5.1"
itertools = "0.13.0"
log = "0.4.22"
md5 = "0.7.0"
serde = { version = "1.0.210", features = ["serde_derive"] }
serde-big-array = "0.5.1"
serde_yml = "0.0.12"
symphonia = "0.5.4"
walkdir = "2.5.0"
