# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2024 Mike Robeson [dijksterhuis]

image: "rust:latest"

stages:
  - build

.build:
  stage: build
  tags:
    - saas-linux-small-amd64
  variables:
    TARGET: x86_64-unknown-linux-gnu
  before_script:
    - |
      apt-get update -yqq
      apt-get -yqq install --no-install-recommends podman
      cargo install cross
  script:
    - cross build --release --target $TARGET
  after_script:
    - find ./target -type f -name "*octatools*" -exec cp {} ./octatools.$TARGET \;
  artifacts:
    paths:
      - ./octatools.$TARGET
  rules:
    # only run on branches when an MRs is open
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - resources/**
          - serde_octatrack/**
          - src/**
          - cicd.yml
        compare_to: main
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-x86-linux-gnu:
  extends: .build

build-arm-linux-gnu:
  extends: .build
  variables:
    TARGET: aarch64-unknown-linux-gnu

#build-x86-windows-gnu:
#  extends: .build
#  tags:
#    - saas-linux-medium-amd64
#  variables:
#    TARGET: x86_64-pc-windows-gnu
