# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2024 Mike Robeson [dijksterhuis]

include:
  - local: ".gitlab/builds/merge-request.yml"
    # only run when the branch has a merge request open
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
        changes:
          - octatools-bin/**
          - octatools-lib/**
          - octatools-py/**
          - .gitlab/**
          - data/**
  # only run binary release steps when a main tag push
  - local: ".gitlab/releases/binary.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG
  # TODO
  #- local: ".gitlab/releases/cargo.yml"
  #  rules:
  #    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG
  # TODO
  #- local: ".gitlab/releases/python.yml"
  #  rules:
  #    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG

stages:
  - build
  - test
  - check
  - release

# naive test run, only run when a branch push and no open merge requests for the
# branch
test-plain:
  stage: test
  tags:
    - saas-linux-small-amd64
  script:
    - cargo test --workspace --no-fail-fast
  rules:
    - if: $CI_DEFAULT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
