# "borrowed" and modified from:
# https://github.com/open-contracting/cardinal-rs/blob/main/.github/workflows/release.yml

name: Release octatools-bin on tag push
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
            gh release create \
              ${{ github.ref_name }} \
              --title "octatools-bin [${{ github.ref_name }}]" \
              --verify-tag
  assets:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-intel
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
            bin_fname: octatools-bin
          - build: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross
            bin_fname: octatools-bin
          - build: windows-intel
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: cross
            bin_fname: octatools-bin.exe
          - build: macos-intel
            os: macos-latest
            target: x86_64-apple-darwin
            command: cargo
            bin_fname: octatools-bin
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
            command: cargo
            bin_fname: octatools-bin
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          ${{ matrix.command }} build --bin octatools-bin --release --target ${{ matrix.target }}

          DIRNAME="octatools-bin_${{ github.ref_name }}_${{ matrix.target }}"
          mkdir "$DIRNAME"
          cp \
            LICENSE.md \
            README.md \
            "target/${{ matrix.target }}/release/${{ matrix.bin_fname }}" \
            "$DIRNAME"
          7z a "$DIRNAME.zip" "$DIRNAME"

          gh release upload ${{ github.ref_name }} "$DIRNAME.zip"
